version: '3.7'

services:
  my-backend:
    image: asia.gcr.io/busker-368211/my-backend:9.0
    platform: linux/x86_64
    build:
      context: .
      dockerfile: Dockerfile
    # volumes:
    #   - ./src:/myfolder/src
    ports:
      - 3000:3000
    # env_file:
    #   - ./.env.prod
